"""Connect transactions with user and wallet

Revision ID: 45a18717465a
Revises: 7789bd1ebb7c
Create Date: 2023-12-22 10:46:39.718587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45a18717465a'
down_revision: Union[str, None] = '7789bd1ebb7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('transactions', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('transactions', sa.Column('wallet_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_name_wallet_value_date_type', 'transactions', ['name', 'wallet_id', 'value', 'date', 'type'])
    op.create_foreign_key(None, 'transactions', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'transactions', 'wallets', ['wallet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint('unique_name_wallet_value_date_type', 'transactions', type_='unique')
    op.drop_column('transactions', 'wallet_id')
    op.drop_column('transactions', 'user_id')
    op.drop_column('transactions', 'date')
    # ### end Alembic commands ###
