"""Change constraint value

Revision ID: 48c57f973e94
Revises: 45a18717465a
Create Date: 2023-12-22 13:19:01.718624

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c57f973e94'
down_revision: Union[str, None] = '45a18717465a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_name_wallet_value_date_type', table_name='transactions')
    op.create_unique_constraint('unique_name_wallet_date', 'transactions', ['name', 'wallet_id', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_name_wallet_date', 'transactions', type_='unique')
    op.create_index('unique_name_wallet_value_date_type', 'transactions', ['name', 'wallet_id', 'value', 'date', 'type'], unique=False)
    # ### end Alembic commands ###
