"""Connect category with user

Revision ID: 7320603872bc
Revises: 613067282ac7
Create Date: 2023-12-20 10:26:57.019553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7320603872bc'
down_revision: Union[str, None] = '613067282ac7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint('unique_user_name', 'categories', ['name', 'user_id'])
    op.create_foreign_key(None, 'categories', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'categories', type_='foreignkey')
    op.drop_constraint('unique_user_name', 'categories', type_='unique')
    op.drop_column('categories', 'user_id')
    # ### end Alembic commands ###
