"""Add transfer option to transaction

Revision ID: 84d976747ee1
Revises: aba8d7f50db8
Create Date: 2024-01-14 13:52:08.830590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '84d976747ee1'
down_revision: Union[str, None] = 'aba8d7f50db8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_transfer', sa.Boolean(), nullable=False))
    op.alter_column('transactions', 'subject_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.alter_column('transactions', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transactions', 'category_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.alter_column('transactions', 'subject_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_column('transactions', 'is_transfer')
    # ### end Alembic commands ###
