"""Connect transactions with subject

Revision ID: da8e894532e3
Revises: 48c57f973e94
Create Date: 2023-12-31 00:18:34.933034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da8e894532e3'
down_revision: Union[str, None] = '48c57f973e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('subject_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'subject_id')
    # ### end Alembic commands ###
