name: Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint-and-type-check:
    name: Source Code Verifying
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          path: 'backend'

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.5

      - name: Install poetry
        run:
          pip install poetry

      - name: Install dependencies
        run:
          poetry install

      - name: Integration tests
        run:
          poetry run pytest

      - name: Mypy type checking
        run:
          poetry run mypy .

      - name: Pylint code linting
        run:
          poetry run pylint backend